var score = 500;
var arr1 = ["Awais","Shan","Ijaz"];
var arr2 = [320,230,420];
var a = arr1[0];
var b = arr1[1];
var c = arr1[2];
var d = arr2[0];
var e = arr2[1];
var f = arr2[2];
var percent1 = (d/score*100);
var percent2 = (e/score*100);
var percent3 = (f/score*100);
alert("Score of "+a+" is "+d+". "+percent1+"%");
alert("Score of "+b+" is "+e+". "+percent2+"%");
alert("Score of "+c+" is "+f+". "+percent3+"%");
console.log("Score of "+a+" is "+d+". "+percent1+"%");
console.log("Score of "+b+" is "+e+". "+percent2+"%");
console.log("Score of "+c+" is "+f+". "+percent3+"%");